name: Terraform CD

on:
  push:
    branches:
      - main
    paths:
      - "*.tf"
      - "**/*.tf"
      - "lambda/**"
      - ".terraform.lock.hcl"
      - ".github/workflows/terraform-cd.yml"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-apply
  cancel-in-progress: false

jobs:
  terraform-apply:
    name: Plan and apply
    runs-on: ubuntu-latest
    timeout-minutes: 45

    env:
      AWS_REGION: eu-central-1
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.16.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: arn:aws:iam::432342420991:role/aws-iac-lab-dev-github-apply-role
          role-session-name: terraform-cd
          aws-region: ${{ env.AWS_REGION }}
          allowed-account-ids: "432342420991"

      - name: Check formatting
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Terraform plan
        run: terraform plan \
          -input=false \
          -lock-timeout=5m \
          -out=tfplan

      - name: Terraform apply
        run: terraform apply -input=false tfplan
        